title: Kieran Hayes
email: kieran@khayes.ie
description: >- # this means to ignore newlines until "baseurl:"
  Kieran Hayes software engineer.
baseurl: ""
url: "https://khayes.ie" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: khayes_ie
github_username:  khayes

sass:
  style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag