title: Kieran Hayes
email: kieran@khayes.ie
description: >- # this means to ignore newlines until "baseurl:"
  Kieran Hayes software engineer.
baseurl: ""
twitter_username: khayes_ie
github_username:  khayes
permalink: /blog/post/:slug
excerpt_separator: <!--read_more-->

sass:
  style: compressed
  sass_dir: _sass

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag