version: '3'
services:
    jekyll:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: khayes_ie
        environment:
            - JEKYLL_ENV=docker
        command: jekyll serve --force_polling --livereload 
        ports:
            - 4000:4000
            - 35729:35729
        volumes:
            - .:/srv/jekyll